# Generated by Django 6.0.1 on 2026-01-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_borrowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='owner',
        ),
    ]
