# Generated by Django 6.0.1 on 2026-01-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_remove_tool_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('active', 'On Loan'), ('pending', 'Awaiting Review'), ('returned', 'Returned/Available'), ('disputed', 'Disputed')], default='active', max_length=20),
        ),
    ]
