# Generated by Django 6.0.1 on 2026-01-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_remove_borrowing_is_returned_borrowing_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('active', 'On Loan'), ('pending', 'Awaiting Review'), ('returned', 'Available'), ('disputed', 'Disputed')], default='active', max_length=20),
        ),
    ]
