# Generated by Django 6.0.1 on 2026-01-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_alter_borrowing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='user_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
