# Generated by Django 6.0.1 on 2026-01-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_borrowing_user_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='available_back_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
